### ISSUE TITLE
Xposed checker still can detect the xposed after hider

### ISSUE THREAD

**Issue by fpmystar** [Yaerin/XposedHider#8]
Hi Yaerin,

  after I install your xposed hider in the vxp, and I already enable it in the xposed modules. but when I open the xposed checker, it still can list the xposed, still the hider didn't work. there is the log of xposed.
[xposed_error_20181024_172452.log](https://github.com/Yaerin/XposedHider/files/2509844/xposed_error_20181024_172452.log)

**Comment by w568w** [comment]
Hi fpmystar,  
  
There's nothing wrong in your log file,which has neither any exceptions nor error outputs.  
Further information(eg. the inspective result of `Xposed Checker` and your `Virtual Xposed`'s version) should be provided,thanks.

**Comment by w568w** [comment]
Also, `xposed hider` may not work properly in `Virtual Xposed` at the moment.  
It'll not be fixed until `Virtual Xposed`'s support.

[VirtualXposed's instruction](https://github.com/android-hacker/VirtualXposed/blob/exposed/README.md)
```
The only two restriction of VirtualXposed are:

Unable to modify system, so any Module which modifies system won't be able to work properly.
Currently resource hooks are not supported. (Theming modules use Resource Hooks).
```
