### ISSUE TITLE
有些应用不显示在列表里，可能是，这些应用隐藏了自己。

### ISSUE THREAD

**Issue by 873578156** [Yaerin/XposedHider#9]
有些应用不显示在列表里，可能是，这些应用隐藏了自己。

**Comment by w568w** [comment]
Hi 873578156，

确定你给予了XposedHider访问应用列表权限吗？

**Comment by 873578156** [comment]
是的，我确认，因为其他的应用可以在列表中看到。

**Comment by LiarOnce** [comment]
我清除了 Xposed Hider 的数据就正常了，不过没隐藏成功。。。。。。

**Comment by KagurazakaHanabi** [comment]
讲真这是个很神奇的问题，从第一个版本起就有了，不明白是什么引起的

**Comment by w568w** [comment]
@KagurazakaHanabi 尝试不要使用SQLite缓存读取，可能是数据库读取或写入中的问题。
